site_name: Platform

# Meta tags (placed in header)
site_description: 
#site_author: Your Name
#site_url: https://you.github.io/diagrams

# Repository (add link to repository on each page)
#repo_name: diagrams
#repo_url: http://github.com/you/diagrams
#edit_uri: edit/master/src/main/doc/docs/

#Copyright (shown at the footer)
#copyright: 'Copyright &copy; 2017 Your Name'

docs_dir: "site"

# Meterial theme
theme:
  name: 'material'
  locale: "en"
  language: "en"
  feature:
    tabs: false

plugins:
  - search
  - markdownextradata
  - build_plantuml:
      render: "server"
      output_format: svg
      diagram_root: "site"
      output_folder: "images"
      input_folder: "."
      input_extensions: "plantuml,puml"
      server: "http://plantuml:8080"

#    Required for variables support (https://github.com/rosscdh/mkdocs-markdownextradata-plugin)

#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/you
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/you


# Google Analytics
#google_analytics:
#  - 'UA-111111111-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

nav:
  - Home: index.md
  - Architecture:
      - Main Component: "components/main/index.md"
  - Flows:
      - Test Flow: "flows/test-flow/index.md"
