name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      plantuml:
        image: plantuml/plantuml-server
        ports:
          - "8100:8080"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          architecture: 'x86'
      - uses: action/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force --site-dir docs --config-file ${GITHUB_WORKSPACE}/src/main/mkdocs/mkdocs.yml
