name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      plantuml:
        image: plantuml/plantuml-server
        ports:
          - "8100:8080"
    steps:
      - name: Checkout Project
      - uses: actions/checkout@v2
      - name: Build PlantUML SVG
        uses: docker://miy4/plantuml
        with:
          args: -tsvg -charset utf-8 -r -dir${GITHUB_WORKSPACE}/src/main/mkdocs/site/images -I${GITHUB_WORKSPACE}/src/main/mkdocs/site/*.puml
      - name: Build MkDocs and Publish
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material mkdocs-markdownextradata-plugin mkdocs-build-plantuml-plugin
      - run: mkdocs gh-deploy --force --site-dir docs --config-file ${GITHUB_WORKSPACE}/src/main/mkdocs/mkdocs.yml
